import { getAuthUser } from '@/actions/user';
import Navbar from '@/components/Navbar';
import ThemeProvider from '@/components/theme/Provider';
import { Toaster } from '@/components/ui/toaster';
import { UserProvider } from '@/components/user/UserProvider';
import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import React from 'react';
import './globals.css';

const font = Rubik({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: 'Lovalova App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const user = await getAuthUser();

  return (
    <html suppressHydrationWarning={true} lang="ru">
      <body className={font.className}>
        <UserProvider user={user}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <Navbar title="lovalova" />
            {children}
            <Toaster />
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
